export type ProductVisibility = 'visible' | 'hidden' | 'rejected';

export type HabbaProduct = {
  slug: string;
  titleAr: string;
  titleEn: string;
  category: 'Bracelets' | 'Necklaces' | 'Sets';
  categoryAr: 'أساور' | 'عقود' | 'أطقم';
  collection: string;
  collectionAr: string;
  image: string;
  priceLabelAr: 'السعر عند الطلب';
  priceLabelEn: 'Ask for price';
  status: 'available';
  statusAr: 'متاح للطلب';
  featured: boolean;
  visibility: ProductVisibility;
  descriptionAr: string;
  descriptionEn: string;
  tags: string[];
};

export const whatsappNumber = '201011549509';

export const allProducts: HabbaProduct[] = [
  { slug: 'colorful-star-set', titleAr: 'طقم النجوم الملونة', titleEn: 'Colorful Star Set', category: 'Sets', categoryAr: 'أطقم', collection: 'Colorful Star Collection', collectionAr: 'كولرفل ستار', image: '/images/habba/products/hbb-colorful-star-set-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: true, visibility: 'visible', descriptionAr: 'طقم خرز ملون بتفاصيل نجوم لطيفة، مناسب لهدية بسيطة أو لمسة مرحة في اليوم.', descriptionEn: 'A colorful bead set with soft star details, made for everyday playfulness or simple gifting.', tags: ['set', 'stars', 'colorful', 'giftable', 'handmade'] },
  { slug: 'green-speckle-bracelet', titleAr: 'أسورة خضراء مرقطة', titleEn: 'Green Speckled Bracelet', category: 'Bracelets', categoryAr: 'أساور', collection: 'Green Mood Collection', collectionAr: 'جرين مود', image: '/images/habba/products/hbb-green-speckle-bracelet-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: true, visibility: 'visible', descriptionAr: 'أسورة بدرجات أخضر هادية ولمسة مرقطة خفيفة، سهلة في اللبس اليومي.', descriptionEn: 'A calm green bracelet with soft speckled details, easy to wear every day.', tags: ['bracelet', 'green', 'speckled', 'daily', 'handmade'] },
  { slug: 'lavender-rose-bracelet', titleAr: 'أسورة لافندر بوردة', titleEn: 'Lavender Rose Bracelet', category: 'Bracelets', categoryAr: 'أساور', collection: 'Cute Gift Collection', collectionAr: 'هدايا صغيرة', image: '/images/habba/products/hbb-lavender-rose-bracelet-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: true, visibility: 'visible', descriptionAr: 'أسورة ناعمة بلون لافندر مع وردة صغيرة، لطيفة كهدية أو تفصيلة هادية.', descriptionEn: 'A soft lavender bracelet with a tiny rose detail, gentle and giftable.', tags: ['bracelet', 'lavender', 'rose', 'giftable', 'soft'] },
  { slug: 'red-heart-bracelet', titleAr: 'أسورة القلب الأحمر', titleEn: 'Red Heart Bracelet', category: 'Bracelets', categoryAr: 'أساور', collection: 'Cute Gift Collection', collectionAr: 'هدايا صغيرة', image: '/images/habba/products/hbb-red-heart-bracelet-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: true, visibility: 'visible', descriptionAr: 'أسورة بسيطة بقلب أحمر صغير، تضيف لمسة دافئة ومرحة من غير مبالغة.', descriptionEn: 'A simple bracelet with a tiny red heart for a warm playful touch.', tags: ['bracelet', 'heart', 'red', 'giftable', 'cute'] },
  { slug: 'blue-star-heishi-bracelet', titleAr: 'أسورة النجمة الزرقاء', titleEn: 'Blue Star Bracelet', category: 'Bracelets', categoryAr: 'أساور', collection: 'Colorful Star Collection', collectionAr: 'كولرفل ستار', image: '/images/habba/products/hbb-blue-star-heishi-bracelet-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: true, visibility: 'visible', descriptionAr: 'أسورة بدرجات أزرق وتفاصيل نجوم، خفيفة وسهلة التنسيق.', descriptionEn: 'A blue bracelet with star details, light and easy to style.', tags: ['bracelet', 'blue', 'stars', 'daily', 'colorful'] },
  { slug: 'aqua-speckle-bracelet', titleAr: 'أسورة أكوا مرقطة', titleEn: 'Aqua Speckled Bracelet', category: 'Bracelets', categoryAr: 'أساور', collection: 'Green Mood Collection', collectionAr: 'جرين مود', image: '/images/habba/products/hbb-aqua-speckle-bracelet-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: true, visibility: 'visible', descriptionAr: 'أسورة أكوا بتفاصيل مرقطة هادية، مناسبة للبس اليومي والستايل الخفيف.', descriptionEn: 'An aqua speckled bracelet with a calm everyday feel.', tags: ['bracelet', 'aqua', 'speckled', 'daily', 'soft'] },
  { slug: 'pastel-candy-bracelet', titleAr: 'أسورة ألوان باستيل', titleEn: 'Pastel Candy Bracelet', category: 'Bracelets', categoryAr: 'أساور', collection: 'Cute Gift Collection', collectionAr: 'هدايا صغيرة', image: '/images/habba/products/hbb-pastel-candy-bracelet-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: true, visibility: 'visible', descriptionAr: 'أسورة بألوان باستيل لطيفة، شكلها خفيف ومناسب كهدية صغيرة.', descriptionEn: 'A sweet pastel bracelet that feels light, colorful, and giftable.', tags: ['bracelet', 'pastel', 'giftable', 'colorful', 'soft'] },
  { slug: 'white-daisy-smile-necklace', titleAr: 'عقد دايزي سمايل', titleEn: 'White Daisy Smile Necklace', category: 'Necklaces', categoryAr: 'عقود', collection: 'Cute Gift Collection', collectionAr: 'هدايا صغيرة', image: '/images/habba/products/hbb-white-daisy-smile-necklace-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: true, visibility: 'visible', descriptionAr: 'عقد أبيض خفيف بتفاصيل دايزي وسمايل، مناسب للوك يومي مرح.', descriptionEn: 'A light white necklace with daisy and smile details for a cheerful everyday look.', tags: ['necklace', 'white', 'daisy', 'smile', 'giftable'] },
  { slug: 'red-flower-necklace', titleAr: 'عقد الوردة الحمراء', titleEn: 'Red Flower Necklace', category: 'Necklaces', categoryAr: 'عقود', collection: 'Cute Gift Collection', collectionAr: 'هدايا صغيرة', image: '/images/habba/products/hbb-red-flower-necklace-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: false, visibility: 'visible', descriptionAr: 'عقد بتفصيلة وردة حمراء صغيرة، قطعة مبهجة وسهلة اللبس.', descriptionEn: 'A necklace with a tiny red flower detail, cheerful and easy to wear.', tags: ['necklace', 'red', 'flower', 'giftable', 'cute'] },
  { slug: 'coral-flower-bracelet', titleAr: 'أسورة وردة كورال', titleEn: 'Coral Flower Bracelet', category: 'Bracelets', categoryAr: 'أساور', collection: 'Cute Gift Collection', collectionAr: 'هدايا صغيرة', image: '/images/habba/products/hbb-coral-flower-bracelet-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: false, visibility: 'visible', descriptionAr: 'أسورة كورال بتفصيلة وردة صغيرة، لطيفة للبس اليومي أو هدية بسيطة.', descriptionEn: 'A coral bracelet with a small flower detail, lovely for daily wear or gifting.', tags: ['bracelet', 'coral', 'flower', 'giftable', 'soft'] },
  { slug: 'green-flower-drop-bracelet', titleAr: 'أسورة الوردة الخضراء', titleEn: 'Green Flower Bracelet', category: 'Bracelets', categoryAr: 'أساور', collection: 'Green Mood Collection', collectionAr: 'جرين مود', image: '/images/habba/products/hbb-green-flower-drop-bracelet-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: false, visibility: 'visible', descriptionAr: 'أسورة خضراء بتفصيلة وردة ناعمة، مناسبة للستايل الهادي.', descriptionEn: 'A green bracelet with a soft flower detail, made for calm styling.', tags: ['bracelet', 'green', 'flower', 'daily', 'soft'] },
  { slug: 'berry-frost-bracelet', titleAr: 'أسورة بيري هادية', titleEn: 'Berry Frost Bracelet', category: 'Bracelets', categoryAr: 'أساور', collection: 'Soft Color Collection', collectionAr: 'ألوان ناعمة', image: '/images/habba/products/hbb-berry-frost-bracelet-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: false, visibility: 'visible', descriptionAr: 'أسورة بدرجات بيري ناعمة، سهلة التنسيق ومناسبة لتفصيلة يومية.', descriptionEn: 'A bracelet in gentle berry tones, easy to match with everyday outfits.', tags: ['bracelet', 'berry', 'soft-colors', 'daily', 'calm'] },
  { slug: 'sage-neutral-bracelet', titleAr: 'أسورة سيج هادية', titleEn: 'Sage Neutral Bracelet', category: 'Bracelets', categoryAr: 'أساور', collection: 'Green Mood Collection', collectionAr: 'جرين مود', image: '/images/habba/products/hbb-sage-neutral-bracelet-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: false, visibility: 'visible', descriptionAr: 'أسورة بدرجات سيج محايدة، بسيطة وخفيفة للبس اليومي.', descriptionEn: 'A neutral sage bracelet with a simple everyday feel.', tags: ['bracelet', 'sage', 'neutral', 'daily', 'calm'] },
  { slug: 'lime-green-seed-necklace', titleAr: 'عقد أخضر لايم', titleEn: 'Lime Green Necklace', category: 'Necklaces', categoryAr: 'عقود', collection: 'Green Mood Collection', collectionAr: 'جرين مود', image: '/images/habba/products/hbb-lime-green-seed-necklace-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: false, visibility: 'visible', descriptionAr: 'عقد بدرجة لايم منعشة، خفيف ومناسب للستايل اليومي.', descriptionEn: 'A fresh lime-green necklace for light everyday styling.', tags: ['necklace', 'green', 'lime', 'daily', 'fresh'] },
  { slug: 'smoky-grey-bracelet', titleAr: 'أسورة رمادي هادي', titleEn: 'Smoky Grey Bracelet', category: 'Bracelets', categoryAr: 'أساور', collection: 'Calm Basics', collectionAr: 'أساسيات هادية', image: '/images/habba/products/hbb-smoky-grey-bracelet-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: false, visibility: 'visible', descriptionAr: 'أسورة رمادي هادية لمحبي القطع البسيطة والناعمة.', descriptionEn: 'A calm grey bracelet for simple, quiet everyday looks.', tags: ['bracelet', 'grey', 'calm-basics', 'daily', 'neutral'] },
  { slug: 'pink-smiley-bracelet', titleAr: 'أسورة سمايلي وردي', titleEn: 'Pink Smiley Bracelet', category: 'Bracelets', categoryAr: 'أساور', collection: 'Cute Gift Collection', collectionAr: 'هدايا صغيرة', image: '/images/habba/products/hbb-pink-smiley-bracelet-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: false, visibility: 'visible', descriptionAr: 'أسورة وردي بتفصيلة سمايلي صغيرة، مرحة من غير ما تبقى طفولية زيادة.', descriptionEn: 'A pink bracelet with a tiny smiley detail, playful but still soft.', tags: ['bracelet', 'pink', 'smiley', 'giftable', 'playful'] },
  { slug: 'green-flower-necklace', titleAr: 'عقد وردة خضراء', titleEn: 'Green Flower Necklace', category: 'Necklaces', categoryAr: 'عقود', collection: 'Green Mood Collection', collectionAr: 'جرين مود', image: '/images/habba/products/hbb-green-flower-necklace-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: false, visibility: 'visible', descriptionAr: 'عقد أخضر بتفصيلة وردة ناعمة، مناسب للوك بسيط وهادي.', descriptionEn: 'A green necklace with a soft flower detail for a simple calm look.', tags: ['necklace', 'green', 'flower', 'daily', 'soft'] },
  { slug: 'simple-green-beaded-necklace', titleAr: 'عقد أخضر بسيط', titleEn: 'Simple Green Necklace', category: 'Necklaces', categoryAr: 'عقود', collection: 'Green Mood Collection', collectionAr: 'جرين مود', image: '/images/habba/products/hbb-simple-green-beaded-necklace-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: false, visibility: 'visible', descriptionAr: 'عقد أخضر بسيط وخفيف، مناسب للبس اليومي من غير تفاصيل كتير.', descriptionEn: 'A simple green necklace, light and easy for everyday wear.', tags: ['necklace', 'green', 'simple', 'daily', 'calm'] },
  { slug: 'colorful-flower-bracelet', titleAr: 'أسورة ورد ملون', titleEn: 'Colorful Flower Bracelet', category: 'Bracelets', categoryAr: 'أساور', collection: 'Cute Gift Collection', collectionAr: 'هدايا صغيرة', image: '/images/habba/products/hbb-colorful-flower-bracelet-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: false, visibility: 'visible', descriptionAr: 'أسورة بألوان مبهجة وتفاصيل ورد صغيرة، لطيفة ومرحة.', descriptionEn: 'A colorful bracelet with tiny flower details, cheerful and easy to wear.', tags: ['bracelet', 'colorful', 'flower', 'giftable', 'playful'] },
  { slug: 'pink-strawberry-necklace', titleAr: 'عقد فراولة وردي', titleEn: 'Pink Strawberry Necklace', category: 'Necklaces', categoryAr: 'عقود', collection: 'Cute Gift Collection', collectionAr: 'هدايا صغيرة', image: '/images/habba/products/hbb-pink-strawberry-necklace-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: false, visibility: 'visible', descriptionAr: 'عقد وردي بتفصيلة فراولة لطيفة، مناسب كهدية صغيرة أو لوك مرح.', descriptionEn: 'A pink necklace with a sweet strawberry detail, cute and giftable.', tags: ['necklace', 'pink', 'strawberry', 'giftable', 'cute'] },
  { slug: 'blue-bead-necklace', titleAr: 'عقد أزرق بسيط', titleEn: 'Blue Bead Necklace', category: 'Necklaces', categoryAr: 'عقود', collection: 'Calm Basics', collectionAr: 'أساسيات هادية', image: '/images/habba/products/hbb-blue-bead-necklace-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: false, visibility: 'visible', descriptionAr: 'عقد أزرق بسيط، خفيف وسهل يتلبس مع إطلالة يومية.', descriptionEn: 'A simple blue bead necklace for light everyday styling.', tags: ['necklace', 'blue', 'simple', 'daily', 'calm'] },
  { slug: 'wooden-bead-necklace-set', titleAr: 'عقد خرز خشبي', titleEn: 'Wooden Bead Necklace Set', category: 'Necklaces', categoryAr: 'عقود', collection: 'Natural Collection', collectionAr: 'ناتشورال', image: '/images/habba/products/hbb-wooden-bead-necklace-set-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: false, visibility: 'visible', descriptionAr: 'عقد بخامات شكلها طبيعي وهادي، مناسب لمحبي التفاصيل البسيطة.', descriptionEn: 'A calm necklace set with a natural beaded feel and simple styling.', tags: ['necklace', 'natural', 'wooden', 'calm', 'simple'] },
  { slug: 'olive-aqua-bracelet', titleAr: 'أسورة أوليف أكوا', titleEn: 'Olive Aqua Bracelet', category: 'Bracelets', categoryAr: 'أساور', collection: 'Green Mood Collection', collectionAr: 'جرين مود', image: '/images/habba/products/hbb-olive-aqua-bracelet-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: false, visibility: 'hidden', descriptionAr: 'داخليًا: القطعة محتاجة مراجعة بصرية قبل الإتاحة.', descriptionEn: 'Internal: needs visual review before being made visible.', tags: ['bracelet', 'hidden', 'review'] },
  { slug: 'neutral-beaded-necklace', titleAr: 'عقد نيوترال بيد', titleEn: 'Neutral Beaded Necklace', category: 'Necklaces', categoryAr: 'عقود', collection: 'Natural Collection', collectionAr: 'ناتشورال', image: '/images/habba/products/hbb-neutral-beaded-necklace-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: false, visibility: 'hidden', descriptionAr: 'داخليًا: المنتج قيد مراجعة شكل نهائي.', descriptionEn: 'Internal: pending final visual check.', tags: ['necklace', 'hidden', 'review'] },
  { slug: 'black-gold-line-bracelet', titleAr: 'أسورة بلاك جولد لاين', titleEn: 'Black Gold-Line Bracelet', category: 'Bracelets', categoryAr: 'أساور', collection: 'Calm Basics', collectionAr: 'أساسيات هادية', image: '/images/habba/products/hbb-black-gold-line-bracelet-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: false, visibility: 'rejected', descriptionAr: 'داخليًا: مرفوضة حاليًا لأنها خارج هوية البراند.', descriptionEn: 'Internal: rejected for now as off-brand.', tags: ['bracelet', 'rejected', 'off-brand'] },
  { slug: 'orange-beaded-tally-counter', titleAr: 'كاونتر خرز برتقالي', titleEn: 'Orange Beaded Tally Counter', category: 'Bracelets', categoryAr: 'أساور', collection: 'Custom Experiments', collectionAr: 'تجارب خاصة', image: '/images/habba/products/hbb-orange-beaded-tally-counter-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: false, visibility: 'rejected', descriptionAr: 'داخليًا: تجربة خاصة وليست منتج إطلاق مناسب.', descriptionEn: 'Internal: experiment item, not suitable for launch catalog.', tags: ['rejected', 'experiment'] }
];

export const visibleProducts = allProducts.filter((product) => product.visibility === 'visible');
export const hiddenProducts = allProducts.filter((product) => product.visibility === 'hidden');
export const rejectedProducts = allProducts.filter((product) => product.visibility === 'rejected');
export const featuredProducts = visibleProducts.filter((product) => product.featured).slice(0, 8);

export const launchProducts = visibleProducts;

export const createWhatsAppLink = (productNameAr: string) => {
  const msg = `أهلًا، حابة أسأل عن ${productNameAr} — هل متاحة؟ وسعرها كام؟`;
  return `https://wa.me/${whatsappNumber}?text=${encodeURIComponent(msg)}`;
};
