export type HabbaProduct = {
  slug: string;
  titleAr: string;
  titleEn: string;
  category: 'Bracelets' | 'Necklaces' | 'Sets';
  categoryAr: 'أساور' | 'عقود' | 'أطقم';
  collection: string;
  collectionAr: string;
  image: string;
  priceLabelAr: 'السعر عند الطلب';
  priceLabelEn: 'Ask for price';
  status: 'available';
  statusAr: 'متاح للطلب';
  featured: boolean;
  descriptionAr: string;
  descriptionEn: string;
  tags: string[];
};

export const whatsappNumber = '201011549509';

export const launchProducts: HabbaProduct[] = [
  { slug: 'colorful-star-set', titleAr: 'طقم كولرفل ستار', titleEn: 'Colorful Star Set', category: 'Sets', categoryAr: 'أطقم', collection: 'Colorful Star Collection', collectionAr: 'كولرفل ستار', image: '/images/habba/products/hbb-colorful-star-set-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: true, descriptionAr: 'طقم خرز handmade بألوان مبهجة مع تفاصيل نجوم، مناسب للاستخدام اليومي أو هدية بسيطة.', descriptionEn: 'A handmade colorful bead set with star details, easy for daily wear or simple gifting.', tags: ['set', 'stars', 'colorful', 'handmade', 'giftable'] },
  { slug: 'green-speckle-bracelet', titleAr: 'أسورة جرين سبكل', titleEn: 'Green Speckle Bracelet', category: 'Bracelets', categoryAr: 'أساور', collection: 'Green Mood Collection', collectionAr: 'جرين مود', image: '/images/habba/products/hbb-green-speckle-bracelet-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: true, descriptionAr: 'أسورة خرز handmade بدرجات أخضر لطيفة وتفاصيل مرقطة، مناسبة للبس اليومي أو كهدية بسيطة.', descriptionEn: 'A handmade green bead bracelet with soft speckled details, made for everyday wear or simple gifting.', tags: ['bracelet', 'green', 'speckled', 'handmade', 'giftable'] },
  { slug: 'lavender-rose-bracelet', titleAr: 'أسورة لافندر روز', titleEn: 'Lavender Rose Bracelet', category: 'Bracelets', categoryAr: 'أساور', collection: 'Cute Gift Collection', collectionAr: 'هدايا صغيرة', image: '/images/habba/products/hbb-lavender-rose-bracelet-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: true, descriptionAr: 'أسورة handmade بلون لافندر هادي مع وردة صغيرة، لطيفة للبس الخفيف أو هدية بسيطة.', descriptionEn: 'A handmade lavender bracelet with a small rose detail, lovely for light wear or gifting.', tags: ['bracelet', 'lavender', 'rose', 'handmade', 'giftable'] },
  { slug: 'red-heart-bracelet', titleAr: 'أسورة القلب الأحمر', titleEn: 'Red Heart Bracelet', category: 'Bracelets', categoryAr: 'أساور', collection: 'Cute Gift Collection', collectionAr: 'هدايا صغيرة', image: '/images/habba/products/hbb-red-heart-bracelet-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: true, descriptionAr: 'أسورة خرز handmade بقلب أحمر صغير، قطعة بسيطة تعطي لمسة دافئة على اللوك.', descriptionEn: 'A handmade beaded bracelet with a small red heart for a warm everyday touch.', tags: ['bracelet', 'heart', 'red', 'handmade', 'giftable'] },
  { slug: 'blue-star-heishi-bracelet', titleAr: 'أسورة بلو ستار', titleEn: 'Blue Star Heishi Bracelet', category: 'Bracelets', categoryAr: 'أساور', collection: 'Colorful Star Collection', collectionAr: 'كولرفل ستار', image: '/images/habba/products/hbb-blue-star-heishi-bracelet-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: true, descriptionAr: 'أسورة handmade بتدرجات أزرق مع تفاصيل نجوم، مريحة وتناسب اللبس اليومي.', descriptionEn: 'A handmade blue bracelet with star details, easy to style for daily outfits.', tags: ['bracelet', 'blue', 'stars', 'handmade', 'daily'] },
  { slug: 'aqua-speckle-bracelet', titleAr: 'أسورة أكوا سبكل', titleEn: 'Aqua Speckle Bracelet', category: 'Bracelets', categoryAr: 'أساور', collection: 'Green Mood Collection', collectionAr: 'جرين مود', image: '/images/habba/products/hbb-aqua-speckle-bracelet-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: true, descriptionAr: 'أسورة خرز handmade بألوان أكوا هادية وتفاصيل مرقطة خفيفة، مناسبة لكل يوم.', descriptionEn: 'A handmade aqua bead bracelet with light speckled accents for everyday wear.', tags: ['bracelet', 'aqua', 'speckled', 'handmade', 'daily'] },
  { slug: 'pastel-candy-bracelet', titleAr: 'أسورة باستيل كاندي', titleEn: 'Pastel Candy Bracelet', category: 'Bracelets', categoryAr: 'أساور', collection: 'Cute Gift Collection', collectionAr: 'هدايا صغيرة', image: '/images/habba/products/hbb-pastel-candy-bracelet-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: true, descriptionAr: 'أسورة handmade بألوان باستيل ناعمة، خيار بسيط ولطيف للبس اليومي أو الهدية.', descriptionEn: 'A handmade pastel bracelet, simple and sweet for daily styling or gifting.', tags: ['bracelet', 'pastel', 'colorful', 'handmade', 'giftable'] },
  { slug: 'white-daisy-smile-necklace', titleAr: 'عقد دايزي سمايل الأبيض', titleEn: 'White Daisy Smile Necklace', category: 'Necklaces', categoryAr: 'عقود', collection: 'Cute Gift Collection', collectionAr: 'هدايا صغيرة', image: '/images/habba/products/hbb-white-daisy-smile-necklace-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: true, descriptionAr: 'عقد handmade باللون الأبيض مع تفاصيل ديزي وسمايل، خفيف ومناسب للإطلالات اليومية.', descriptionEn: 'A handmade white necklace with daisy and smile details, light for everyday looks.', tags: ['necklace', 'white', 'daisy', 'handmade', 'giftable'] },
  { slug: 'red-flower-necklace', titleAr: 'عقد الورد الأحمر', titleEn: 'Red Flower Necklace', category: 'Necklaces', categoryAr: 'عقود', collection: 'Cute Gift Collection', collectionAr: 'هدايا صغيرة', image: '/images/habba/products/hbb-red-flower-necklace-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: false, descriptionAr: 'عقد handmade بتفاصيل وردة حمراء، قطعة مبهجة وتناسب مناسبات بسيطة.', descriptionEn: 'A handmade necklace with a red flower detail, cheerful and easy for simple occasions.', tags: ['necklace', 'red', 'flower', 'handmade', 'giftable'] },
  { slug: 'coral-flower-bracelet', titleAr: 'أسورة كورال فلاور', titleEn: 'Coral Flower Bracelet', category: 'Bracelets', categoryAr: 'أساور', collection: 'Cute Gift Collection', collectionAr: 'هدايا صغيرة', image: '/images/habba/products/hbb-coral-flower-bracelet-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: false, descriptionAr: 'أسورة خرز handmade بلون كورال مع وردة صغيرة، لطيفة للبس اليومي أو كهدية.', descriptionEn: 'A handmade coral beaded bracelet with a small flower, lovely for daily wear or gifting.', tags: ['bracelet', 'coral', 'flower', 'handmade', 'giftable'] },
  { slug: 'green-flower-drop-bracelet', titleAr: 'أسورة جرين فلاور', titleEn: 'Green Flower Drop Bracelet', category: 'Bracelets', categoryAr: 'أساور', collection: 'Green Mood Collection', collectionAr: 'جرين مود', image: '/images/habba/products/hbb-green-flower-drop-bracelet-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: false, descriptionAr: 'أسورة handmade بتفصيلة وردة خضراء ناعمة، مناسبة للستايل الهادئ والبسيط.', descriptionEn: 'A handmade bracelet with a soft green flower detail for calm, simple styling.', tags: ['bracelet', 'green', 'flower', 'handmade', 'daily'] },
  { slug: 'berry-frost-bracelet', titleAr: 'أسورة بيري فروست', titleEn: 'Berry Frost Bracelet', category: 'Bracelets', categoryAr: 'أساور', collection: 'Soft Color Collection', collectionAr: 'ألوان ناعمة', image: '/images/habba/products/hbb-berry-frost-bracelet-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: false, descriptionAr: 'أسورة خرز handmade بدرجات بيري هادية، خيار عملي وسهل للتنسيق اليومي.', descriptionEn: 'A handmade bracelet in gentle berry tones, practical and easy for everyday outfits.', tags: ['bracelet', 'berry', 'soft-colors', 'handmade', 'daily'] },
  { slug: 'sage-neutral-bracelet', titleAr: 'أسورة سيج الهادية', titleEn: 'Sage Neutral Bracelet', category: 'Bracelets', categoryAr: 'أساور', collection: 'Green Mood Collection', collectionAr: 'جرين مود', image: '/images/habba/products/hbb-sage-neutral-bracelet-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: false, descriptionAr: 'أسورة handmade بدرجات سيج محايدة، بسيطة وتناسب اللبس اليومي بسهولة.', descriptionEn: 'A handmade bracelet in neutral sage tones, simple and easy to wear every day.', tags: ['bracelet', 'sage', 'neutral', 'handmade', 'daily'] },
  { slug: 'lime-green-seed-necklace', titleAr: 'عقد لايم جرين', titleEn: 'Lime Green Seed Necklace', category: 'Necklaces', categoryAr: 'عقود', collection: 'Green Mood Collection', collectionAr: 'جرين مود', image: '/images/habba/products/hbb-lime-green-seed-necklace-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: false, descriptionAr: 'عقد خرز handmade بلون لايم جرين منعش، مناسب للإطلالات اليومية البسيطة.', descriptionEn: 'A handmade lime-green bead necklace, fresh and easy for daily looks.', tags: ['necklace', 'lime', 'green', 'handmade', 'daily'] },
  { slug: 'smoky-grey-bracelet', titleAr: 'أسورة سموكي جراي', titleEn: 'Smoky Grey Bracelet', category: 'Bracelets', categoryAr: 'أساور', collection: 'Calm Basics', collectionAr: 'أساسيات هادية', image: '/images/habba/products/hbb-smoky-grey-bracelet-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: false, descriptionAr: 'أسورة handmade بدرجات رمادي هادي، مناسبة لمحبي القطع البسيطة.', descriptionEn: 'A handmade smoky grey bracelet for those who prefer simple, calm pieces.', tags: ['bracelet', 'grey', 'minimal', 'handmade', 'daily'] },
  { slug: 'pink-smiley-bracelet', titleAr: 'أسورة بينك سمايلي', titleEn: 'Pink Smiley Bracelet', category: 'Bracelets', categoryAr: 'أساور', collection: 'Cute Gift Collection', collectionAr: 'هدايا صغيرة', image: '/images/habba/products/hbb-pink-smiley-bracelet-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: false, descriptionAr: 'أسورة خرز handmade باللون الوردي مع سمايلي صغير، خفيفة ومناسبة كهدية.', descriptionEn: 'A handmade pink beaded bracelet with a tiny smiley detail, light and giftable.', tags: ['bracelet', 'pink', 'smiley', 'handmade', 'giftable'] },
  { slug: 'green-flower-necklace', titleAr: 'عقد جرين فلاور', titleEn: 'Green Flower Necklace', category: 'Necklaces', categoryAr: 'عقود', collection: 'Green Mood Collection', collectionAr: 'جرين مود', image: '/images/habba/products/hbb-green-flower-necklace-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: false, descriptionAr: 'عقد handmade بتفاصيل وردة خضراء ناعمة، مناسب للوك يومي هادي.', descriptionEn: 'A handmade necklace with a soft green flower detail for calm daily styling.', tags: ['necklace', 'green', 'flower', 'handmade', 'daily'] },
  { slug: 'simple-green-beaded-necklace', titleAr: 'عقد جرين بسيط', titleEn: 'Simple Green Beaded Necklace', category: 'Necklaces', categoryAr: 'عقود', collection: 'Green Mood Collection', collectionAr: 'جرين مود', image: '/images/habba/products/hbb-simple-green-beaded-necklace-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: false, descriptionAr: 'عقد خرز handmade أخضر بتصميم بسيط، قطعة عملية للبس اليومي.', descriptionEn: 'A handmade simple green beaded necklace, practical for everyday wear.', tags: ['necklace', 'green', 'beaded', 'handmade', 'minimal'] },
  { slug: 'colorful-flower-bracelet', titleAr: 'أسورة كولرفل فلاور', titleEn: 'Colorful Flower Bracelet', category: 'Bracelets', categoryAr: 'أساور', collection: 'Cute Gift Collection', collectionAr: 'هدايا صغيرة', image: '/images/habba/products/hbb-colorful-flower-bracelet-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: false, descriptionAr: 'أسورة handmade بألوان متنوعة مع وردة صغيرة، مرحة ومناسبة لهدية بسيطة.', descriptionEn: 'A handmade colorful bracelet with a small flower detail, playful and gift-ready.', tags: ['bracelet', 'colorful', 'flower', 'handmade', 'giftable'] },
  { slug: 'pink-strawberry-necklace', titleAr: 'عقد بينك ستروبري', titleEn: 'Pink Strawberry Necklace', category: 'Necklaces', categoryAr: 'عقود', collection: 'Cute Gift Collection', collectionAr: 'هدايا صغيرة', image: '/images/habba/products/hbb-pink-strawberry-necklace-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: false, descriptionAr: 'عقد handmade باللون الوردي مع تفصيلة مستوحاة من الفراولة، مناسب كهدية لطيفة.', descriptionEn: 'A handmade pink necklace with a strawberry-inspired detail, nice for simple gifting.', tags: ['necklace', 'pink', 'strawberry', 'handmade', 'giftable'] },
  { slug: 'blue-bead-necklace', titleAr: 'عقد بلو بيد', titleEn: 'Blue Bead Necklace', category: 'Necklaces', categoryAr: 'عقود', collection: 'Calm Basics', collectionAr: 'أساسيات هادية', image: '/images/habba/products/hbb-blue-bead-necklace-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: false, descriptionAr: 'عقد خرز handmade بدرجات أزرق هادية، سهل التنسيق مع ملابس اليوم.', descriptionEn: 'A handmade blue bead necklace in calm tones, easy to pair with daily outfits.', tags: ['necklace', 'blue', 'beaded', 'handmade', 'minimal'] },
  { slug: 'wooden-bead-necklace-set', titleAr: 'عقد وود بيد', titleEn: 'Wooden Bead Necklace Set', category: 'Necklaces', categoryAr: 'عقود', collection: 'Natural Collection', collectionAr: 'ناتشورال', image: '/images/habba/products/hbb-wooden-bead-necklace-set-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: false, descriptionAr: 'عقد handmade بخرز خشبي ولمسة طبيعية، تصميم بسيط ومريح للاستخدام اليومي.', descriptionEn: 'A handmade wooden-bead necklace with a natural touch and simple daily style.', tags: ['necklace', 'wooden', 'natural', 'handmade', 'daily'] }
];

export const createWhatsAppLink = (productNameAr: string) => {
  const msg = `أهلًا، حابة أسأل عن ${productNameAr} — هل متاحة؟ وسعرها كام؟`;
  return `https://wa.me/${whatsappNumber}?text=${encodeURIComponent(msg)}`;
};
