export type ProductVisibility = 'visible' | 'hidden' | 'rejected';

export type HabbaProduct = {
  slug: string;
  titleAr: string;
  titleEn: string;
  category: 'Bracelets' | 'Necklaces' | 'Sets';
  categoryAr: 'أساور' | 'عقود' | 'أطقم';
  collection: string;
  collectionAr: string;
  image: string;
  priceLabelAr: 'السعر عند الطلب';
  priceLabelEn: 'Ask for price';
  status: 'available';
  statusAr: 'متاح للطلب';
  featured: boolean;
  visibility: ProductVisibility;
  descriptionAr: string;
  descriptionEn: string;
  tags: string[];
};

export const whatsappNumber = '201011549509';

export const allProducts: HabbaProduct[] = [
  { slug: 'colorful-star-set', titleAr: 'طقم كولرفل ستار', titleEn: 'Colorful Star Set', category: 'Sets', categoryAr: 'أطقم', collection: 'Colorful Star Collection', collectionAr: 'كولرفل ستار', image: '/images/habba/products/hbb-colorful-star-set-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: true, visibility: 'visible', descriptionAr: 'طقم ملون بتفاصيل نجوم لطيفة، مناسب لليوم العادي أو هدية بسيطة.', descriptionEn: 'A colorful set with star details, easy for everyday wear or simple gifting.', tags: ['set', 'stars', 'colorful', 'giftable'] },
  { slug: 'green-speckle-bracelet', titleAr: 'أسورة جرين سبكل', titleEn: 'Green Speckle Bracelet', category: 'Bracelets', categoryAr: 'أساور', collection: 'Green Mood Collection', collectionAr: 'جرين مود', image: '/images/habba/products/hbb-green-speckle-bracelet-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: true, visibility: 'visible', descriptionAr: 'أسورة بدرجات أخضر هادية ولمسة مرقطة خفيفة.', descriptionEn: 'A calm green bracelet with light speckled details.', tags: ['bracelet', 'green', 'daily'] },
  { slug: 'lavender-rose-bracelet', titleAr: 'أسورة لافندر روز', titleEn: 'Lavender Rose Bracelet', category: 'Bracelets', categoryAr: 'أساور', collection: 'Cute Gift Collection', collectionAr: 'هدايا صغيرة', image: '/images/habba/products/hbb-lavender-rose-bracelet-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: true, visibility: 'visible', descriptionAr: 'أسورة ناعمة بلون لافندر مع وردة صغيرة.', descriptionEn: 'A soft lavender bracelet with a small rose detail.', tags: ['bracelet', 'lavender', 'giftable'] },
  { slug: 'red-heart-bracelet', titleAr: 'أسورة القلب الأحمر', titleEn: 'Red Heart Bracelet', category: 'Bracelets', categoryAr: 'أساور', collection: 'Cute Gift Collection', collectionAr: 'هدايا صغيرة', image: '/images/habba/products/hbb-red-heart-bracelet-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: true, visibility: 'visible', descriptionAr: 'أسورة بسيطة بقلب أحمر صغير ولمسة مرحة.', descriptionEn: 'A simple bracelet with a small red heart and playful feel.', tags: ['bracelet', 'heart', 'red'] },
  { slug: 'blue-star-heishi-bracelet', titleAr: 'أسورة بلو ستار', titleEn: 'Blue Star Heishi Bracelet', category: 'Bracelets', categoryAr: 'أساور', collection: 'Colorful Star Collection', collectionAr: 'كولرفل ستار', image: '/images/habba/products/hbb-blue-star-heishi-bracelet-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: true, visibility: 'visible', descriptionAr: 'أسورة زرقا بتفاصيل نجوم، خفيفة وسهلة التنسيق.', descriptionEn: 'A blue bracelet with star details, light and easy to style.', tags: ['bracelet', 'blue', 'stars'] },
  { slug: 'aqua-speckle-bracelet', titleAr: 'أسورة أكوا سبكل', titleEn: 'Aqua Speckle Bracelet', category: 'Bracelets', categoryAr: 'أساور', collection: 'Green Mood Collection', collectionAr: 'جرين مود', image: '/images/habba/products/hbb-aqua-speckle-bracelet-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: true, visibility: 'visible', descriptionAr: 'أسورة أكوا مرقطة بتفاصيل هادية تناسب كل يوم.', descriptionEn: 'An aqua speckled bracelet with a calm everyday look.', tags: ['bracelet', 'aqua', 'daily'] },
  { slug: 'pastel-candy-bracelet', titleAr: 'أسورة باستيل كاندي', titleEn: 'Pastel Candy Bracelet', category: 'Bracelets', categoryAr: 'أساور', collection: 'Cute Gift Collection', collectionAr: 'هدايا صغيرة', image: '/images/habba/products/hbb-pastel-candy-bracelet-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: true, visibility: 'visible', descriptionAr: 'أسورة بألوان باستيل لطيفة ومناسبة كهدية.', descriptionEn: 'A pastel bracelet that feels sweet and giftable.', tags: ['bracelet', 'pastel', 'giftable'] },
  { slug: 'white-daisy-smile-necklace', titleAr: 'عقد دايزي سمايل الأبيض', titleEn: 'White Daisy Smile Necklace', category: 'Necklaces', categoryAr: 'عقود', collection: 'Cute Gift Collection', collectionAr: 'هدايا صغيرة', image: '/images/habba/products/hbb-white-daisy-smile-necklace-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: true, visibility: 'visible', descriptionAr: 'عقد أبيض خفيف بتفاصيل ديزي وسمايل.', descriptionEn: 'A light white necklace with daisy and smile details.', tags: ['necklace', 'white', 'giftable'] },
  { slug: 'red-flower-necklace', titleAr: 'عقد الورد الأحمر', titleEn: 'Red Flower Necklace', category: 'Necklaces', categoryAr: 'عقود', collection: 'Cute Gift Collection', collectionAr: 'هدايا صغيرة', image: '/images/habba/products/hbb-red-flower-necklace-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: false, visibility: 'visible', descriptionAr: 'عقد بتفصيلة وردة حمراء ولمسة مبهجة.', descriptionEn: 'A necklace with a red flower detail and cheerful vibe.', tags: ['necklace', 'red', 'flower'] },
  { slug: 'coral-flower-bracelet', titleAr: 'أسورة كورال فلاور', titleEn: 'Coral Flower Bracelet', category: 'Bracelets', categoryAr: 'أساور', collection: 'Cute Gift Collection', collectionAr: 'هدايا صغيرة', image: '/images/habba/products/hbb-coral-flower-bracelet-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: false, visibility: 'visible', descriptionAr: 'أسورة كورال مع وردة صغيرة، مناسبة للبس اليومي.', descriptionEn: 'A coral bracelet with a small flower, great for everyday wear.', tags: ['bracelet', 'coral', 'flower'] },
  { slug: 'green-flower-drop-bracelet', titleAr: 'أسورة جرين فلاور', titleEn: 'Green Flower Drop Bracelet', category: 'Bracelets', categoryAr: 'أساور', collection: 'Green Mood Collection', collectionAr: 'جرين مود', image: '/images/habba/products/hbb-green-flower-drop-bracelet-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: false, visibility: 'visible', descriptionAr: 'أسورة خضراء بتفصيلة وردة ناعمة.', descriptionEn: 'A green bracelet with a soft flower drop detail.', tags: ['bracelet', 'green', 'flower'] },
  { slug: 'berry-frost-bracelet', titleAr: 'أسورة بيري فروست', titleEn: 'Berry Frost Bracelet', category: 'Bracelets', categoryAr: 'أساور', collection: 'Soft Color Collection', collectionAr: 'ألوان ناعمة', image: '/images/habba/products/hbb-berry-frost-bracelet-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: false, visibility: 'visible', descriptionAr: 'أسورة بدرجات بيري هادية وسهلة التنسيق.', descriptionEn: 'A bracelet in gentle berry tones, easy to match daily.', tags: ['bracelet', 'berry', 'soft-colors'] },
  { slug: 'sage-neutral-bracelet', titleAr: 'أسورة سيج الهادية', titleEn: 'Sage Neutral Bracelet', category: 'Bracelets', categoryAr: 'أساور', collection: 'Green Mood Collection', collectionAr: 'جرين مود', image: '/images/habba/products/hbb-sage-neutral-bracelet-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: false, visibility: 'visible', descriptionAr: 'أسورة بدرجات سيج محايدة بإحساس بسيط.', descriptionEn: 'A neutral sage bracelet with a simple everyday feel.', tags: ['bracelet', 'sage', 'neutral'] },
  { slug: 'lime-green-seed-necklace', titleAr: 'عقد لايم جرين', titleEn: 'Lime Green Seed Necklace', category: 'Necklaces', categoryAr: 'عقود', collection: 'Green Mood Collection', collectionAr: 'جرين مود', image: '/images/habba/products/hbb-lime-green-seed-necklace-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: false, visibility: 'visible', descriptionAr: 'عقد لايم جرين منعش ومناسب لستايل يومي.', descriptionEn: 'A fresh lime-green necklace for easy daily styling.', tags: ['necklace', 'green', 'lime'] },
  { slug: 'smoky-grey-bracelet', titleAr: 'أسورة سموكي جراي', titleEn: 'Smoky Grey Bracelet', category: 'Bracelets', categoryAr: 'أساور', collection: 'Calm Basics', collectionAr: 'أساسيات هادية', image: '/images/habba/products/hbb-smoky-grey-bracelet-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: false, visibility: 'visible', descriptionAr: 'أسورة رمادي هادي لمحبي القطع البسيطة.', descriptionEn: 'A calm grey bracelet for simple everyday looks.', tags: ['bracelet', 'grey', 'calm'] },
  { slug: 'pink-smiley-bracelet', titleAr: 'أسورة بينك سمايلي', titleEn: 'Pink Smiley Bracelet', category: 'Bracelets', categoryAr: 'أساور', collection: 'Cute Gift Collection', collectionAr: 'هدايا صغيرة', image: '/images/habba/products/hbb-pink-smiley-bracelet-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: false, visibility: 'visible', descriptionAr: 'أسورة وردي بتفصيلة سمايلي لطيفة.', descriptionEn: 'A pink bracelet with a tiny smiley, fun and giftable.', tags: ['bracelet', 'pink', 'smiley'] },
  { slug: 'green-flower-necklace', titleAr: 'عقد جرين فلاور', titleEn: 'Green Flower Necklace', category: 'Necklaces', categoryAr: 'عقود', collection: 'Green Mood Collection', collectionAr: 'جرين مود', image: '/images/habba/products/hbb-green-flower-necklace-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: false, visibility: 'visible', descriptionAr: 'عقد أخضر بتفصيلة وردة ناعمة وخفيفة.', descriptionEn: 'A green necklace with a soft flower detail.', tags: ['necklace', 'green', 'flower'] },
  { slug: 'simple-green-beaded-necklace', titleAr: 'عقد جرين بسيط', titleEn: 'Simple Green Beaded Necklace', category: 'Necklaces', categoryAr: 'عقود', collection: 'Green Mood Collection', collectionAr: 'جرين مود', image: '/images/habba/products/hbb-simple-green-beaded-necklace-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: false, visibility: 'visible', descriptionAr: 'عقد أخضر بسيط وعملي للاستخدام اليومي.', descriptionEn: 'A simple green beaded necklace made for daily wear.', tags: ['necklace', 'green', 'simple'] },
  { slug: 'colorful-flower-bracelet', titleAr: 'أسورة كولرفل فلاور', titleEn: 'Colorful Flower Bracelet', category: 'Bracelets', categoryAr: 'أساور', collection: 'Cute Gift Collection', collectionAr: 'هدايا صغيرة', image: '/images/habba/products/hbb-colorful-flower-bracelet-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: false, visibility: 'visible', descriptionAr: 'أسورة ملونة مع وردة صغيرة ولمسة مرحة.', descriptionEn: 'A colorful bracelet with a small flower and playful mood.', tags: ['bracelet', 'colorful', 'flower'] },
  { slug: 'pink-strawberry-necklace', titleAr: 'عقد بينك ستروبري', titleEn: 'Pink Strawberry Necklace', category: 'Necklaces', categoryAr: 'عقود', collection: 'Cute Gift Collection', collectionAr: 'هدايا صغيرة', image: '/images/habba/products/hbb-pink-strawberry-necklace-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: false, visibility: 'visible', descriptionAr: 'عقد وردي بتفصيلة مستوحاة من الفراولة.', descriptionEn: 'A pink necklace with a strawberry-inspired detail.', tags: ['necklace', 'pink', 'giftable'] },
  { slug: 'blue-bead-necklace', titleAr: 'عقد بلو بيد', titleEn: 'Blue Bead Necklace', category: 'Necklaces', categoryAr: 'عقود', collection: 'Calm Basics', collectionAr: 'أساسيات هادية', image: '/images/habba/products/hbb-blue-bead-necklace-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: false, visibility: 'visible', descriptionAr: 'عقد أزرق بدرجات هادية وسهل مع كل يوم.', descriptionEn: 'A calm blue bead necklace that works with everyday outfits.', tags: ['necklace', 'blue', 'calm'] },
  { slug: 'wooden-bead-necklace-set', titleAr: 'عقد وود بيد', titleEn: 'Wooden Bead Necklace Set', category: 'Necklaces', categoryAr: 'عقود', collection: 'Natural Collection', collectionAr: 'ناتشورال', image: '/images/habba/products/hbb-wooden-bead-necklace-set-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: false, visibility: 'visible', descriptionAr: 'عقد بطابع طبيعي وتصميم بسيط للاستخدام اليومي.', descriptionEn: 'A natural-style necklace with a simple, daily look.', tags: ['necklace', 'natural', 'daily'] },
  { slug: 'olive-aqua-bracelet', titleAr: 'أسورة أوليف أكوا', titleEn: 'Olive Aqua Bracelet', category: 'Bracelets', categoryAr: 'أساور', collection: 'Green Mood Collection', collectionAr: 'جرين مود', image: '/images/habba/products/hbb-olive-aqua-bracelet-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: false, visibility: 'hidden', descriptionAr: 'داخليًا: القطعة محتاجة مراجعة بصرية قبل الإتاحة.', descriptionEn: 'Internal: needs visual review before being made visible.', tags: ['bracelet', 'hidden', 'review'] },
  { slug: 'neutral-beaded-necklace', titleAr: 'عقد نيوترال بيد', titleEn: 'Neutral Beaded Necklace', category: 'Necklaces', categoryAr: 'عقود', collection: 'Natural Collection', collectionAr: 'ناتشورال', image: '/images/habba/products/hbb-neutral-beaded-necklace-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: false, visibility: 'hidden', descriptionAr: 'داخليًا: المنتج قيد مراجعة شكل نهائي.', descriptionEn: 'Internal: pending final visual check.', tags: ['necklace', 'hidden', 'review'] },
  { slug: 'black-gold-line-bracelet', titleAr: 'أسورة بلاك جولد لاين', titleEn: 'Black Gold-Line Bracelet', category: 'Bracelets', categoryAr: 'أساور', collection: 'Calm Basics', collectionAr: 'أساسيات هادية', image: '/images/habba/products/hbb-black-gold-line-bracelet-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: false, visibility: 'rejected', descriptionAr: 'داخليًا: مرفوضة حاليًا لأنها خارج هوية البراند.', descriptionEn: 'Internal: rejected for now as off-brand.', tags: ['bracelet', 'rejected', 'off-brand'] },
  { slug: 'orange-beaded-tally-counter', titleAr: 'كاونتر خرز برتقالي', titleEn: 'Orange Beaded Tally Counter', category: 'Bracelets', categoryAr: 'أساور', collection: 'Custom Experiments', collectionAr: 'تجارب خاصة', image: '/images/habba/products/hbb-orange-beaded-tally-counter-card.png', priceLabelAr: 'السعر عند الطلب', priceLabelEn: 'Ask for price', status: 'available', statusAr: 'متاح للطلب', featured: false, visibility: 'rejected', descriptionAr: 'داخليًا: تجربة خاصة وليست منتج إطلاق مناسب.', descriptionEn: 'Internal: experiment item, not suitable for launch catalog.', tags: ['rejected', 'experiment'] }
];

export const visibleProducts = allProducts.filter((product) => product.visibility === 'visible');
export const hiddenProducts = allProducts.filter((product) => product.visibility === 'hidden');
export const rejectedProducts = allProducts.filter((product) => product.visibility === 'rejected');
export const featuredProducts = visibleProducts.filter((product) => product.featured).slice(0, 8);

export const launchProducts = visibleProducts;

export const createWhatsAppLink = (productNameAr: string) => {
  const msg = `أهلًا، حابة أسأل عن ${productNameAr} — هل متاحة؟ وسعرها كام؟`;
  return `https://wa.me/${whatsappNumber}?text=${encodeURIComponent(msg)}`;
};
