import { NextRequest, NextResponse } from 'next/server';
import { visibleProducts, type HabbaProduct } from '@/content/habba-products';

type DropInput={dropMood:'soft-gift'|'green-calm'|'colorful-day'|'cute-pieces'|'everyday-calm'|'natural-simple';dropSize:4|5|6;focusType:'mixed'|'bracelets'|'necklaces'|'giftable';colorDirection:'surprise'|'green'|'pink'|'blue'|'colorful'|'neutral';optionalNote?:string};
type Pick={slug:string;reasonAr:string};
const WINDOW_MS=600000,LIMIT=8,ipHits=new Map<string,number[]>();
const sets={dropMood:new Set(['soft-gift','green-calm','colorful-day','cute-pieces','everyday-calm','natural-simple']),dropSize:new Set([4,5,6]),focusType:new Set(['mixed','bracelets','necklaces','giftable']),colorDirection:new Set(['surprise','green','pink','blue','colorful','neutral'])};
const moodTokens={ 'soft-gift':['giftable','soft','cute','pastel','lavender','daisy','flower'],'green-calm':['green','aqua','sage','lime','calm','daily','green-mood'],'colorful-day':['colorful','stars','pastel','playful','set'],'cute-pieces':['cute','heart','smile','strawberry','flower','giftable'],'everyday-calm':['daily','simple','calm','neutral','grey','sage'],'natural-simple':['natural','wooden','neutral','simple','calm']} as const;
const colorTokens={green:['green','aqua','lime','sage'],pink:['pink','lavender','berry','pastel'],blue:['blue','aqua'],colorful:['colorful','stars','playful','pastel'],neutral:['neutral','grey','sage','natural']} as const;
const checkLimit=(ip:string)=>{const now=Date.now();const recent=(ipHits.get(ip)||[]).filter((t)=>now-t<=WINDOW_MS);if(recent.length>=LIMIT)return false;recent.push(now);ipHits.set(ip,recent);return true;};
function score(p:HabbaProduct,input:DropInput){let s=0;const b=`${p.titleAr} ${p.titleEn} ${p.descriptionAr} ${p.collectionAr} ${p.categoryAr} ${p.tags.join(' ')}`.toLowerCase();moodTokens[input.dropMood].forEach((t)=>{if(b.includes(t))s+=3;});if(input.focusType==='bracelets'&&p.category==='Bracelets')s+=8;if(input.focusType==='necklaces'&&p.category==='Necklaces')s+=8;if(input.focusType==='giftable'&&(b.includes('giftable')||b.includes('هدايا')))s+=5;if(input.colorDirection!=='surprise')colorTokens[input.colorDirection].forEach((t)=>{if(b.includes(t))s+=2;});return s;}
function fallback(input:DropInput){const sorted=[...visibleProducts].sort((a,b)=>score(b,input)-score(a,input)||a.slug.localeCompare(b.slug));const picks:HabbaProduct[]=[];if(input.focusType==='mixed'){for(const p of sorted){if(picks.length>=input.dropSize)break;if(!picks.some((x)=>x.category===p.category))picks.push(p);}}for(const p of sorted){if(picks.length>=input.dropSize)break;if(!picks.some((x)=>x.slug===p.slug))picks.push(p);}return picks.slice(0,input.dropSize);}
const makeWa=(name:string,ps:HabbaProduct[])=>`أهلًا، حابة أسأل عن الـ Drop ده:\n${name}\n${ps.map((p)=>`- ${p.titleAr}`).join('\n')}\nهل متاحين؟ والتفاصيل إيه؟`;

export async function POST(req:NextRequest){const ip=req.headers.get('x-forwarded-for')?.split(',')[0]?.trim()||'unknown';if(!checkLimit(ip))return NextResponse.json({error:'طلبات كتير في وقت قصير، جربي بعد شوية.'},{status:429});const body=await req.json().catch(()=>null) as Partial<DropInput>|null;const optionalNote=(body?.optionalNote||'').trim();if(!body||!sets.dropMood.has(body.dropMood as string)||!sets.dropSize.has(body.dropSize as number)||!sets.focusType.has(body.focusType as string)||!sets.colorDirection.has(body.colorDirection as string)||optionalNote.length>120)return NextResponse.json({error:'البيانات غير صحيحة.'},{status:400});
const input:DropInput={dropMood:body.dropMood as DropInput['dropMood'],dropSize:body.dropSize as 4|5|6,focusType:body.focusType as DropInput['focusType'],colorDirection:body.colorDirection as DropInput['colorDirection'],optionalNote};const fb=fallback(input);const rs=new Map(fb.map((p)=>[p.slug,'قطعة مناسبة مع مود الـ Drop اللي اخترتيه.']));const validSet=new Set(visibleProducts.map((p)=>p.slug));
const format=(source:'ai'|'fallback',picks:Pick[],copy:Record<string,string|undefined>={},heroSlug?:string)=>{const products=picks.map((x)=>visibleProducts.find((p)=>p.slug===x.slug)).filter((p):p is HabbaProduct=>Boolean(p));const hero=products.find((p)=>p.slug===heroSlug)||products[0];const name=copy.dropNameAr||'Drop حبّة ناعم';return NextResponse.json({dropNameAr:name,dropSubtitleAr:copy.dropSubtitleAr||'اختيارات صغيرة على مودك من الكتالوج المتاح.',dropStoryAr:copy.dropStoryAr||'جمعنالك قطع قريبة من ذوقك في Drop بسيط ينفع هدية أو لنفسك.',heroProduct:{slug:hero.slug,titleAr:hero.titleAr,titleEn:hero.titleEn,image:hero.image,categoryAr:hero.categoryAr,collectionAr:hero.collectionAr},products:products.map((p)=>({slug:p.slug,titleAr:p.titleAr,titleEn:p.titleEn,image:p.image,categoryAr:p.categoryAr,collectionAr:p.collectionAr,reasonAr:picks.find((x)=>x.slug===p.slug)?.reasonAr||rs.get(p.slug)||'قطعة مناسبة.'})),instagramCaptionAr:copy.instagramCaptionAr||`Drop صغير ومبهج من حبّة 💛`,whatsappMessageAr:copy.whatsappMessageAr||makeWa(name,products),source});};
const key=process.env.OPENAI_API_KEY;if(!key)return format('fallback',fb.map((p)=>({slug:p.slug,reasonAr:rs.get(p.slug)!})));const catalog=visibleProducts.map(({slug,titleAr,titleEn,category,categoryAr,collection,collectionAr,descriptionAr,tags})=>({slug,titleAr,titleEn,category,categoryAr,collection,collectionAr,descriptionAr,tags}));
try{const aiRes=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${key}`},body:JSON.stringify({model:process.env.OPENAI_MODEL||'gpt-4o-mini',input:[{role:'system',content:`Return strict JSON only. Pick exactly ${input.dropSize} unique slugs from catalog only. Arabic-first concise. No prices or luxury/gold/crystal/diamonds/healing/energy/gemstones language.`},{role:'user',content:JSON.stringify({input,catalog,outputSchema:{dropNameAr:'string',dropSubtitleAr:'string',dropStoryAr:'string',heroSlug:'string',items:[{slug:'string',reasonAr:'string'}],instagramCaptionAr:'string',whatsappMessageAr:'string'}})}],max_output_tokens:650})});const raw=await aiRes.json();const parsed=JSON.parse(raw?.output_text||'{}') as Record<string,unknown>;const valid=Array.isArray(parsed.items)?Array.from(new Map(parsed.items.filter((i):i is Pick=>typeof i==='object'&&i!==null&&typeof (i as {slug?:unknown}).slug==='string'&&typeof (i as {reasonAr?:unknown}).reasonAr==='string').map((i)=>[i.slug,{slug:i.slug,reasonAr:i.reasonAr.trim()||'قطعة مناسبة للـ Drop.'}])).values()).filter((i)=>validSet.has(i.slug)):[];const padded=[...valid];for(const p of fb){if(padded.length>=input.dropSize)break;if(!padded.some((x)=>x.slug===p.slug))padded.push({slug:p.slug,reasonAr:rs.get(p.slug)!});}const picks=padded.slice(0,input.dropSize);const hero=typeof parsed.heroSlug==='string'&&picks.some((p)=>p.slug===parsed.heroSlug)?parsed.heroSlug:picks[0]?.slug;return format('ai',picks,{dropNameAr:typeof parsed.dropNameAr==='string'?parsed.dropNameAr:undefined,dropSubtitleAr:typeof parsed.dropSubtitleAr==='string'?parsed.dropSubtitleAr:undefined,dropStoryAr:typeof parsed.dropStoryAr==='string'?parsed.dropStoryAr:undefined,instagramCaptionAr:typeof parsed.instagramCaptionAr==='string'?parsed.instagramCaptionAr:undefined,whatsappMessageAr:typeof parsed.whatsappMessageAr==='string'?parsed.whatsappMessageAr:undefined},hero);}catch{return format('fallback',fb.map((p)=>({slug:p.slug,reasonAr:rs.get(p.slug)!})));}}
